import os
import subprocess
import asyncio
try:
    import edge_tts
except ImportError:
    subprocess.run(["pip", "install", "edge-tts"])
    import edge_tts

# --- SCRIPTS ---
intro_script = "Welcome to GHOST—the ultimate Developer Security Operations Sentinel. Built for Engineering leads facing two A M fire-drills. Our 5-agent architecture automatically catches hardcoded secrets and zero-day vulnerabilities from public databases before they reach production."
demo_script = "In this demonstration, we showcase our Universal Ingestion Engine. We begin by configuring our API key and inputting a standard Public GitHub URL along with the error log. While we can easily toggle between GitHub Connect tokens, direct ZIP file uploads, and Private Git tokens, we proceed here with the public URL to run the investigation. Under the hood, GHOST orchestrates 5 specialized agents. Our Detective parses the stack trace and extracts the raw diff. Next, the Security Pariah Agent runs a comprehensive 6-layer Certified Ethical Hacker scan, checking for secrets, static vulnerabilities, and public database threats. If a vulnerability is detected, our Orchestrator—The Bouncer Gate—steps in. It strictly prohibits the Remediation Engineer from generating a patch until the secret is securely removed. We then scroll through the comprehensive security output, carefully reviewing the specific rules that were triggered and the remediation steps provided. You can see how GHOST generates a clean, unified code patch that safely replaces hardcoded variables with secure environment implementations. Next to it is a custom pytest regression suite generated by our Testsmith, ensuring this specific leak never happens again in the future. We then securely download the full incident report and view the detailed text file, which serves as a perfect immutable artifact for compliance audits. Finally, we toggle our Local Model feature, demonstrating seamless integration with Ollama to run the exact same investigation one hundred percent locally and completely offline. With smart context truncation and strict API token economy controls, GHOST turns fifteen minutes of panic into forty-five seconds of secure, verified, and automated resolution."

outro_script = "GHOST is the premier Developer Security Operations solution built for enterprise adoption. It is perfectly designed for organizations demanding rigorous security compliance and speed, including major technology firms like Google, Microsoft Corporation, Amazon Web Services, and Meta Platforms. We welcome collaboration from the open source community and are highly driven to push this technology forward. Submitted for the micro1 Hackathon, by Brian Kioko. Thank you for watching."

# --- GENERATE VOICES ---
print("🎙️ Generating AI Voices...")
async def generate_audio(text, output_file):
    communicate = edge_tts.Communicate(text, "en-US-ChristopherNeural")
    await communicate.save(output_file)

async def main():
    await generate_audio(intro_script, "intro_voice.mp3")
    await generate_audio(demo_script, "demo_voice.mp3")
    await generate_audio(outro_script, "outro_voice.mp3")

asyncio.run(main())

# --- 1. DYNAMIC INTRO SLIDE (Cinematic Zoom on AI Background) ---
print("🎬 Creating Dynamic Intro Slide using FFmpeg...")
with open("title.txt", "w") as f: f.write("GHOST: DevSecOps Sentinel")
with open("b1.txt", "w") as f: f.write("6-Layer CEH Superweapon")
with open("b2.txt", "w") as f: f.write("Universal Ingestion Engine")
with open("b3.txt", "w") as f: f.write("45-Second Incident Resolution")

bg_image = "/home/tristan/.gemini/antigravity/brain/06aa01ed-d5af-44b0-b14c-eab45bcee368/cybersecurity_ai_background_1788082685681.jpg"

intro_filter = (
    f"[0:v]scale=1280:720,zoompan=z='min(zoom+0.0005,1.1)':d=1000:s=1280x720,"
    "colorchannelmixer=rr=0.5:gg=0.5:bb=0.6[bg];"
    "[bg]"
    "drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:"
    "textfile=title.txt:fontcolor=white:fontsize=64:x=(w-text_w)/2:y=200:"
    "box=1:boxcolor=black@0.6:boxborderw=20:alpha='if(lt(t,1),0,if(lt(t,2),t-1,1))',"
    "drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:"
    "textfile=b1.txt:fontcolor=white:fontsize=48:x=(w-text_w)/2:y=350:"
    "box=1:boxcolor=darkblue@0.7:boxborderw=15:alpha='if(lt(t,4),0,if(lt(t,4.5),(t-4)*2,1))',"
    "drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:"
    "textfile=b2.txt:fontcolor=white:fontsize=48:x=(w-text_w)/2:y=450:"
    "box=1:boxcolor=darkblue@0.7:boxborderw=15:alpha='if(lt(t,8),0,if(lt(t,8.5),(t-8)*2,1))',"
    "drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:"
    "textfile=b3.txt:fontcolor=white:fontsize=48:x=(w-text_w)/2:y=550:"
    "box=1:boxcolor=darkblue@0.7:boxborderw=15:alpha='if(lt(t,12),0,if(lt(t,12.5),(t-12)*2,1))'[v]"
)

subprocess.run([
    "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
    "-i", bg_image,
    "-i", "intro_voice.mp3",
    "-filter_complex", intro_filter,
    "-map", "[v]", "-map", "1:a",
    "-c:v", "libx264", "-c:a", "aac", "-r", "30", "-ar", "44100", "-pix_fmt", "yuv420p",
    "-shortest", "intro_slide.mp4"
])

# --- 2. DEMO VIDEO ---
print("🎬 Processing Screen Recording with Voiceover...")
subprocess.run([
    "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
    "-i", "GHOST-Report.mp4",
    "-i", "demo_voice.mp3",
    "-filter_complex", "[0:v]scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2:color=black,setsar=1[v_scaled];[v_scaled]tpad=stop_mode=clone:stop_duration=60[v]",
    "-map", "[v]", "-map", "1:a",
    "-c:v", "libx264", "-c:a", "aac", "-r", "30", "-ar", "44100", "-pix_fmt", "yuv420p",
    "-shortest", "demo_narrated.mp4"
])

# --- 3. OUTRO SLIDE ---
print("🎬 Creating Outro Slide...")
with open("outro_title.txt", "w") as f: f.write("GHOST: Enterprise Ready")
with open("o1.txt", "w") as f: f.write("Built for Google, Microsoft,")
with open("o2.txt", "w") as f: f.write("Amazon Web Services & Meta")
with open("o3.txt", "w") as f: f.write("Submitted by Brian Kioko")

outro_filter = (
    f"[0:v]scale=1280:720,zoompan=z='min(zoom+0.0005,1.1)':d=1000:s=1280x720,"
    "colorchannelmixer=rr=0.5:gg=0.5:bb=0.6[bg];"
    "[bg]"
    "drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:"
    "textfile=outro_title.txt:fontcolor=white:fontsize=64:x=(w-text_w)/2:y=200:"
    "box=1:boxcolor=black@0.6:boxborderw=20:alpha='if(lt(t,1),0,if(lt(t,2),t-1,1))',"
    "drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:"
    "textfile=o1.txt:fontcolor=white:fontsize=48:x=(w-text_w)/2:y=350:"
    "box=1:boxcolor=darkred@0.7:boxborderw=15:alpha='if(lt(t,3),0,if(lt(t,3.5),(t-3)*2,1))',"
    "drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:"
    "textfile=o2.txt:fontcolor=white:fontsize=48:x=(w-text_w)/2:y=450:"
    "box=1:boxcolor=darkred@0.7:boxborderw=15:alpha='if(lt(t,5),0,if(lt(t,5.5),(t-5)*2,1))',"
    "drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:"
    "textfile=o3.txt:fontcolor=white:fontsize=48:x=(w-text_w)/2:y=550:"
    "box=1:boxcolor=darkred@0.7:boxborderw=15:alpha='if(lt(t,9),0,if(lt(t,9.5),(t-9)*2,1))'[v]"
)

subprocess.run([
    "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
    "-i", bg_image,
    "-i", "outro_voice.mp3",
    "-filter_complex", outro_filter,
    "-map", "[v]", "-map", "1:a",
    "-c:v", "libx264", "-c:a", "aac", "-r", "30", "-ar", "44100", "-pix_fmt", "yuv420p",
    "-shortest", "outro_slide.mp4"
])

# --- 4. CONCATENATE ALL ---
print("🎬 Concatenating Intro, Demo, and Outro...")
with open("concat_list.txt", "w") as f:
    f.write("file 'intro_slide.mp4'\n")
    f.write("file 'demo_narrated.mp4'\n")
    f.write("file 'outro_slide.mp4'\n")

subprocess.run([
    "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
    "-f", "concat", "-safe", "0", "-i", "concat_list.txt",
    "-c", "copy", "ghost_final_pitch.mp4"
])

# Cleanup
for file in ["intro_voice.mp3", "demo_voice.mp3", "outro_voice.mp3", "intro_slide.mp4", "demo_narrated.mp4", "outro_slide.mp4", "concat_list.txt", "title.txt", "b1.txt", "b2.txt", "b3.txt", "outro_title.txt", "o1.txt", "o2.txt", "o3.txt"]:
    if os.path.exists(file):
        os.remove(file)

print("✅ SUCCESS! Ultimate Flawless Video generated: ghost_final_pitch.mp4")
