import os
import subprocess
import asyncio
try:
    import edge_tts
except ImportError:
    subprocess.run(["pip", "install", "edge-tts"])
    import edge_tts

# --- SCRIPTS ---
intro_script = "Welcome to GHOST—the DevSecOps Sentinel. Built for SRE leads facing two A M fire-drills. Our 5-agent architecture automatically catches hardcoded secrets and CVE vulnerabilities from public databases before they reach production."

demo_script = "As you can see in this demonstration, we've built a Universal Ingestion Engine to eliminate the biggest pain point in DevSecOps: code access. We support frictionless integration through GitHub Connect tokens, direct ZIP file uploads, and Private Git tokens. While we're toggling through these options to show their flexibility, we will use a standard Public URL for this exact run. We simply input the URL, target branch, and paste the error log. Under the hood, GHOST orchestrates 5 specialized agents. Our Detective parses the stack trace and extracts the raw diff. Next, the Security Pariah Agent runs a comprehensive 6-layer Certified Ethical Hacker scan, checking for secrets, static vulnerabilities, and zero-day CVEs using OSV and NVD public databases. If a vulnerability is detected, our Orchestrator—The Bouncer Gate—steps in. It legally prohibits the Remediation Engineer from generating a patch until the secret is securely removed. GHOST then outputs a clean, unified code patch, ready to download, alongside a custom pytest regression suite generated by our Testsmith. With smart context truncation and strict API token economy controls, GHOST turns fifteen minutes of two A M panic into forty-five seconds of secure, verified, and automated resolution. Thank you."

outro_script = "Submitted for the micro1 Hackathon, by Brian Kioko."

# --- GENERATE VOICES ---
print("🎙️ Generating AI Voices...")
async def generate_audio(text, output_file):
    communicate = edge_tts.Communicate(text, "en-US-ChristopherNeural")
    await communicate.save(output_file)

async def main():
    await generate_audio(intro_script, "intro_voice.mp3")
    await generate_audio(demo_script, "demo_voice.mp3")
    await generate_audio(outro_script, "outro_voice.mp3")

asyncio.run(main())

# --- 1. DYNAMIC INTRO SLIDE (Cinematic Zoom on AI Background) ---
print("🎬 Creating Dynamic Intro Slide using FFmpeg...")
with open("title.txt", "w") as f: f.write("GHOST: DevSecOps Sentinel")
with open("b1.txt", "w") as f: f.write("6-Layer CEH Superweapon")
with open("b2.txt", "w") as f: f.write("Universal Ingestion Engine")
with open("b3.txt", "w") as f: f.write("45-Second Incident Resolution")

bg_image = "/home/tristan/.gemini/antigravity/brain/06aa01ed-d5af-44b0-b14c-eab45bcee368/cybersecurity_ai_background_1788082685681.jpg"

intro_filter = (
    f"[0:v]scale=1280:720,zoompan=z='min(zoom+0.0005,1.1)':d=500:s=1280x720,"
    "colorchannelmixer=rr=0.5:gg=0.5:bb=0.6[bg];"
    "[bg]"
    "drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:"
    "textfile=title.txt:fontcolor=white:fontsize=64:x=(w-text_w)/2:y=200:"
    "box=1:boxcolor=black@0.6:boxborderw=20:alpha='if(lt(t,1),0,if(lt(t,2),t-1,1))',"
    "drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:"
    "textfile=b1.txt:fontcolor=white:fontsize=48:x=(w-text_w)/2:y=350:"
    "box=1:boxcolor=darkblue@0.7:boxborderw=15:alpha='if(lt(t,4),0,if(lt(t,4.5),(t-4)*2,1))',"
    "drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:"
    "textfile=b2.txt:fontcolor=white:fontsize=48:x=(w-text_w)/2:y=450:"
    "box=1:boxcolor=darkblue@0.7:boxborderw=15:alpha='if(lt(t,8),0,if(lt(t,8.5),(t-8)*2,1))',"
    "drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:"
    "textfile=b3.txt:fontcolor=white:fontsize=48:x=(w-text_w)/2:y=550:"
    "box=1:boxcolor=darkblue@0.7:boxborderw=15:alpha='if(lt(t,12),0,if(lt(t,12.5),(t-12)*2,1))'[v]"
)

# Do NOT pad the intro audio, let the shortest (audio) dictate the slide length exactly.
subprocess.run([
    "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
    "-i", bg_image,
    "-i", "intro_voice.mp3",
    "-filter_complex", intro_filter,
    "-map", "[v]", "-map", "1:a",
    "-c:v", "libx264", "-c:a", "aac", "-r", "30", "-ar", "44100", "-pix_fmt", "yuv420p",
    "-shortest", "intro_slide.mp4"
])

# --- 2. DEMO VIDEO ---
print("🎬 Processing Screen Recording with Voiceover...")
subprocess.run([
    "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
    "-i", "hack.mp4",
    "-i", "demo_voice.mp3",
    # Pad video infinitely (tpad) so it doesn't cut off audio early, but DO NOT pad audio.
    # This guarantees -shortest triggers EXACTLY when the voiceover ends.
    "-filter_complex", "[0:v]scale=1280:720:force_original_aspect_ratio=decrease,pad=1280:720:(ow-iw)/2:(oh-ih)/2:color=black,setsar=1[v_scaled];[v_scaled]tpad=stop_mode=clone:stop_duration=60[v]",
    "-map", "[v]", "-map", "1:a",
    "-c:v", "libx264", "-c:a", "aac", "-r", "30", "-ar", "44100", "-pix_fmt", "yuv420p",
    "-shortest", "demo_narrated.mp4"
])

# --- 3. OUTRO SLIDE ---
print("🎬 Creating Outro Slide...")
outro_text = "Submitted for micro1 Hackathon\nBy Brian Kioko"
with open("outro.txt", "w") as f:
    f.write(outro_text)

outro_filter = (
    "color=c=black:s=1280x720:d=5[bg];"
    "[bg]drawtext=fontfile=/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf:"
    "textfile=outro.txt:fontcolor=white:fontsize=64:x=(w-text_w)/2:y=(h-text_h)/2:"
    "alpha='if(lt(t,1),0,if(lt(t,2),t-1,1))'[v]"
)
subprocess.run([
    "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
    "-f", "lavfi", "-i", "color=c=black:s=1280x720:d=5",
    "-i", "outro_voice.mp3",
    "-filter_complex", outro_filter + ";[1:a]apad[a]",
    "-map", "[v]", "-map", "[a]",
    "-c:v", "libx264", "-c:a", "aac", "-r", "30", "-ar", "44100", "-pix_fmt", "yuv420p",
    "-shortest", "outro_slide.mp4"
])

# --- 4. CONCATENATE ALL ---
print("🎬 Concatenating Intro, Demo, and Outro...")
with open("concat_list.txt", "w") as f:
    f.write("file 'intro_slide.mp4'\n")
    f.write("file 'demo_narrated.mp4'\n")
    f.write("file 'outro_slide.mp4'\n")

subprocess.run([
    "ffmpeg", "-hide_banner", "-loglevel", "error", "-y",
    "-f", "concat", "-safe", "0", "-i", "concat_list.txt",
    "-c", "copy", "ghost.mp4"
])

# Cleanup
for file in ["intro_voice.mp3", "demo_voice.mp3", "outro_voice.mp3", "intro_slide.mp4", "demo_narrated.mp4", "outro_slide.mp4", "concat_list.txt", "intro.txt", "outro.txt"]:
    if os.path.exists(file):
        os.remove(file)

print("✅ SUCCESS! Ultimate Flawless Video generated: ghost.mp4")
